---
- name: Print Hello World
  hosts: localhost
  become: false  # You may not need elevated privileges for this task

  tasks:
    - name: Print Hello World
      ansible.builtin.debug:
        msg: "Hello, World!"
